### PR TITLE
WebTorrent Desktop 0.17.0

### PR DESCRIPTION
**Pull request by dcposch**
Checklist
- [x] Test on Mac
- [x] Test on Windows
- [x] Test on Linux
- [ ] Test auto updaters

### CODE REVIEW

**Comment by dcposch** [comment]
https://github.com/feross/webtorrent/pull/928

**Comment by dcposch** [comment]
@grunjol @feross would be cool if someone tried installing the `.deb` file and tested this release on Linux

because we recently added 32- and 64-bit versions, feross might want to test the auto updater

**Comment by dcposch** [comment]
https://github.com/feross/webtorrent-desktop/releases/tag/v0.17.0

**Comment by grunjol** [comment]
Tested on Ubuntu 16.04 64bits. Working fine (and with a very fast startup time!)

**Comment by dcposch** [comment]
Thanks @grunjol  !

I think @feross has a two Windows VMs (32- and 64-bit) the app at v0.16 on them. Let's run them and make sure they auto update correctly.

**Comment by feross** [comment]
I'll test this out shortly.

**Comment by dcposch** [comment]
> It's not easy to test the autoupdater on an unreleased version

We should fix that

**Comment by feross** [comment]
Server is out of space. Looking into it.

**Comment by dcposch** [comment]
webtorrent.io is currently down

How much downtime is there each time we update this repo?

Do we have something like Uptime Robot for webtorrent.io ? I use it for scramble.io and dcpos.ch, it's free and works pretty well

**Comment by feross** [comment]
> Server is out of space. Looking into it.

**Comment by feross** [comment]
> How much downtime is there each time we update this repo?

No more than a second or two. The server is turned off, a couple `mv` commands run (those are instant), then it is started again.

https://github.com/feross/webtorrent-www/blob/master/bin/deploy.sh#L17-L22

> Do we have something like Uptime Robot for webtorrent.io ?

Just signed up. @dcposch I'll add your email to the notification list.

**Comment by feross** [comment]
Okay -- added more storage capacity to the server, the disk resizing I did during the migration a few weeks ago had failed. But it's all good now!

Now -- testing the autoupdater.

**Comment by feross** [comment]
@dcposch Please accept the email invitation so I can add you to the alerts.

**Comment by dcposch** [comment]
done

**Comment by grunjol** [comment]
@dcposch @feross uptimerobot only checks externally if the server is up. I recommend you NewRelic, I have 100+ servers under the free account (only show the last 24hs stats) but you can setup interval server alerts (disk space, I/O, CPU usage) to avoid.

**Comment by feross** [comment]
@dcposch Added you

**Comment by dcposch** [comment]
@grunjol @feross Linode also offers that type of server monitoring (disk space alerts, I/O, CPU). I think you want both. Server monitoring is good but you also want to check that the service is actually up, and Uptime Robot has the advantage of simplicity

I tested the auto updaters on Windows. Installed 0.16 64-bit. Correctly updated to 0.17 64-bit.

Installed 0.15, which only came in 32-bit. Updated to 0.17 32-bit, which then updated to 0.17 64-bit.

Looks good.

**Comment by feross** [comment]
@dcposch Nice. I'm still struggling to get it downloaded over here. GitHub is silly slow. I bet they're throttling us, since we're using around 600GB of bandwidth per month at the moment.

**Comment by feross** [comment]
Issue opened: https://github.com/feross/webtorrent-www/issues/108

**Pull request merged**
