### PR TITLE
Fix raw html showing up on FAQ page (fix #70)

### LINKED ISSUE #70: Raw html from faq page is not interpreted
The code from the youtube videos and the slides are encoded to html entitties and therefore not interpreted by the browser.

### PR DESCRIPTION
**Pull request by feross**

### CODE REVIEW

**Comment by feross** [comment]
I'm going to merge this once the tests pass (without code review) since this is causing the FAQ page to render incorrectly.

Post-review @yciabaud @dcposch

**Comment by yciabaud** [comment]
I believe you have found the right option ;-)

**Comment by dcposch** [comment]
How did this break?

I saw a related problem earlier: the FAQ page just contained the *path to the MD file* rather than rendered content. I fixed it with that hack that we were later able to delete ( https://github.com/feross/webtorrent-www/pull/65/commits/e7bd51a2e41ee8a7e805edde1b9525193db7f19b )

**Comment by feross** [comment]
@dcposch See https://github.com/feross/webtorrent-www/issues/70 for context.

I think that `remarkable` (what we use now) has different assumptions than `marked` about the trustworthiness of the input markdown. It refuses to render HTML unless you explicitly indicate that you want to allow that. Safer default.

**Pull request merged**
